name: Post Reels
on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12PM UTC
  workflow_dispatch:

jobs:
  post-reel:
    runs-on: ubuntu-latest
    env:
      INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
      GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client requests

    - name: Run Reel Poster
      run: python post_reel.py
